version: '3.7'

services:
  slate-client:
    container_name: slate-client
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
      - '.:/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
