version: '3.7'

services:
  slate-share-frontend:
    container_name: slate-share-frontend
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
      - '.:/usr/src/app/node_modules'
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
